name: Build PHP 8.3.2
on:
  workflow_dispatch:
jobs:
  php:
    strategy:
      matrix:
        arch: [x64]
        ts: [nts]
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: php/php-windows-builder/php@v1
        with:
          php-version: '8.3.2'
          arch: ${{ matrix.arch }}
          ts: ${{ matrix.ts }}
